# Generated by Django 5.2.6 on 2025-09-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fichaamortiguador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregenerico', models.CharField(max_length=100)),
                ('nroseriegenerico', models.CharField(max_length=100)),
                ('valorreferencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('stockActual', models.BigIntegerField()),
                ('stockMinimo', models.BigIntegerField()),
                ('stockreservado', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Amortiguador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroSerieamortiguador', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('configuracion', models.TextField()),
                ('fichaamortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.fichaamortiguador')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaingreso', models.DateField()),
                ('horaingreso', models.TimeField()),
                ('estado', models.CharField(max_length=100)),
                ('fechaSalidaEstimada', models.DateField()),
                ('fechaSalidaReal', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('prioridad', models.CharField(max_length=20)),
                ('fechaAsignacion', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('tipoTarea', models.CharField(max_length=100)),
                ('amortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.amortiguador')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.operario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaobservacion', models.DateField()),
                ('horaobservacion', models.TimeField()),
                ('tipoobservacion', models.CharField(max_length=100)),
                ('infoobservacion', models.TextField()),
                ('amortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.amortiguador')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockrecomendado', models.BigIntegerField()),
                ('stockusado', models.BigIntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.tarea')),
            ],
        ),
    ]
