# Generated by Django 5.2.6 on 2025-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortiguador',
            name='configuracion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fechaobservacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='horaobservacion',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='infoobservacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaSalidaReal',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horaingreso',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaAsignacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
