# Generated by Django 5.2.6 on 2025-09-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0002_alter_amortiguador_configuracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortiguador',
            name='configuracion',
            field=models.CharField(default='Sin configurar', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaSalidaEstimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaSalidaReal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipoTarea',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
