# Generated by Django 5.2.6 on 2025-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0003_alter_amortiguador_configuracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaLimite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipoTarea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
