# Generated by Django 5.2.6 on 2025-09-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0004_alter_tarea_fechalimite_alter_tarea_tipotarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaamortiguador',
            name='valorreferencia',
        ),
        migrations.AddField(
            model_name='fichaamortiguador',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fichaamortiguador',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockreservado',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialtarea',
            name='stockusado',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='infoobservacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
