# Generated by Django 5.2.6 on 2025-09-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0005_remove_fichaamortiguador_valorreferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='valordiagrama',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
