# Generated by Django 5.2.6 on 2025-09-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0006_observacion_valordiagrama'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFichaAmortiguador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadrecomendada', models.BigIntegerField()),
                ('fichaamortiguador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.fichaamortiguador')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.material')),
            ],
        ),
    ]
