# Generated by Django 5.2.6 on 2025-10-04 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0007_materialfichaamortiguador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales', models.TextField(help_text='JSON list of missing materials with required/available')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amortiguador.tarea')),
            ],
        ),
    ]
