# Generated by Django 5.2.6 on 2025-10-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0008_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='stockreservado',
            field=models.BigIntegerField(default=0),
        ),
    ]
