# Generated by Django 5.2.6 on 2026-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0010_operario_role_operario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nombre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.CharField(default='unidad', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockActual',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockMinimo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='stockreservado',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
