# Generated by Django 5.2.6 on 2026-04-30

from django.db import migrations, models


def deduplicar_observaciones(apps, schema_editor):
    Observacion = apps.get_model('amortiguador', 'Observacion')
    duplicados = (
        Observacion.objects.values('tarea_id', 'tipoobservacion')
        .order_by()
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
    )

    for grupo in duplicados:
        observaciones = list(
            Observacion.objects.filter(
                tarea_id=grupo['tarea_id'],
                tipoobservacion=grupo['tipoobservacion'],
            ).order_by('-fechaobservacion', '-horaobservacion', '-id')
        )
        if not observaciones:
            continue

        conservar = observaciones[0]
        for observacion in observaciones[1:]:
            observacion.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0011_material_nombre_material_unidad_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicar_observaciones, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.UniqueConstraint(fields=('tarea', 'tipoobservacion'), name='unique_observacion_por_tipo_tarea'),
        ),
    ]
