# Generated by Django 5.2.6 on 2026-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0012_observacion_unique_tarea_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaamortiguador',
            name='mano_obra_reparacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='costo_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_ultimo_cambio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
