# Generated by Django 5.2.6 on 2026-05-03 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0013_fichaamortiguador_mano_obra_reparacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='observacion',
            name='unique_observacion_por_tipo_tarea',
        ),
        migrations.RenameField(
            model_name='observacion',
            old_name='infoobservacion',
            new_name='detalle_completo',
        ),
        migrations.RenameField(
            model_name='observacion',
            old_name='valordiagrama',
            new_name='valor_diagrama',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='fechaobservacion',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='horaobservacion',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='tipoobservacion',
        ),
        migrations.AddField(
            model_name='observacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observacion',
            name='info_diagrama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='info_fisica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='sugerencia_tecnica',
            field=models.CharField(blank=True, choices=[('control', 'Control'), ('reparacion', 'Reparación')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observacion', to='amortiguador.tarea'),
        ),
    ]
