# Generated by Django 5.2.6 on 2026-05-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0014_remove_observacion_unique_observacion_por_tipo_tarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observacion',
            old_name='detalle_completo',
            new_name='detalle_autogenerado',
        ),
        migrations.RenameField(
            model_name='observacion',
            old_name='info_diagrama',
            new_name='detalle_operario',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='info_fisica',
        ),
    ]
