# Generated by Django 5.2.6 on 2026-05-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0016_proveedor_cuit_alter_proveedor_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operario',
            name='role',
            field=models.CharField(choices=[('operario', 'Operario'), ('encargado', 'Encargado'), ('encargado_materiales', 'Encargado de Materiales')], default='operario', max_length=20),
        ),
    ]
