# Generated by Django 5.2.6 on 2026-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0017_alter_operario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='comentariofinal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
