# Generated by Django 5.2.6 on 2026-05-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0020_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha cuando el pedido cambió a estado terminado', null=True),
        ),
    ]
