# Generated by Django 5.2.6 on 2026-05-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0021_pedido_fecha_finalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_vigencia', models.DateField(help_text='Fecha desde la cual este precio es válido')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precios', to='amortiguador.material')),
            ],
            options={
                'ordering': ['-fecha_de_vigencia'],
            },
        ),
    ]
