# Generated by Django 5.2.6 on 2026-05-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0022_historicopreciomaterial_fecha_de_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopreciomaterial',
            name='fecha_de_vigencia',
            field=models.DateField(default='2026-01-01', help_text='Fecha desde la cual este precio es válido'),
        ),
    ]
