# Generated by Django 5.2.6 on 2026-05-06 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0023_alter_historicopreciomaterial_fecha_de_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopreciomaterial',
            name='fecha_de_vigencia',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha desde la cual este precio es válido'),
        ),
    ]
