# Generated by Django 5.2.6 on 2026-08-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0024_alter_historicopreciomaterial_fecha_de_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio_reparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
