# Generated by Django 5.2.6 on 2026-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0025_tarea_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_ultimo_cambio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
