# Generated by Django 5.2.6 on 2026-08-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0026_pedido_fecha_ultimo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='devuelta',
            field=models.BooleanField(default=False),
        ),
    ]
