# Generated by Django 5.2.6 on 2026-08-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0027_tarea_devuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaamortiguador',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
