# Generated by Django 5.2.6 on 2026-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0028_fichaamortiguador_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_presupuesto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
