# Generated by Django 5.2.6 on 2026-08-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0029_pedido_fecha_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaSalidaEstimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaSalidaReal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el pedido cambió a estado terminado', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_presupuesto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
