# Generated by Django 5.2.6 on 2026-08-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amortiguador', '0031_alter_historicopreciomaterial_fecha_de_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='valor_diagrama_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
